Fix common bug about ceph conf
kungze/kolla-helm pull request #24
Opened 2022-06-22 06:51 UTC by caotingv

2022-06-23 07:25 UTC, jeffyjf commented
这个 pr 的三个 commit 有些乱，需要整理以下，我觉得可以合并成一个 comit 提交

2022-06-23 07:26 UTC, jeffyjf requested changes
这个 commit 貌似没用意义，在下一个 commit 中这些修改又改回去了。

2022-06-23 07:50 UTC, caotingv commented
> 这个 pr 的三个 commit 有些乱，需要整理以下，我觉得可以合并成一个 comit 提交



> 这个 pr 的三个 commit 有些乱，需要整理以下，我觉得可以合并成一个 comit 提交

已合并

2022-06-27 00:53 UTC, jeffyjf approved these changes

2022-06-27 06:01 UTC, jeffyjf requested changes
commit 的标题不是很准确，有的代码修改的地方和 ceph 配置无关。标题可以写 Fix some bugs in `common` chart。然后在分别描述一下这些修改。

2022-06-28 05:53 UTC, jeffyjf requested changes

2022-06-28 05:53 UTC, jeffyjf commented on charts/common/templates/scripts/_ks_register_services.sh.tpl
> +elif [ "$SERVICE_VERSION" ]; then
这个叫 API_VERSION 会比较准确

2022-06-30 10:42 UTC, merged