Add glance chart
kungze/kolla-helm pull request #26
Opened 2022-06-22 06:59 UTC by caotingv

2022-06-23 07:37 UTC, jeffyjf requested changes

2022-06-23 07:37 UTC, jeffyjf commented on charts/glance/templates/_helpers.tpl
> +{{- end }}
注意，文件要以 \n 结束

2022-06-23 08:25 UTC, caotingv commented on charts/glance/templates/_helpers.tpl
> +{{- end }}
已更改

2022-06-27 06:51 UTC, jeffyjf requested changes

2022-06-27 06:51 UTC, jeffyjf commented on .github/workflows/install-openstack-glance.yaml
> +name: Install glance chart
我有个疑问：openstack-dep 的修改还没合并，为什么这个 action 会执行成功呢？

2022-06-27 06:51 UTC, jeffyjf commented on charts/glance/Chart.yaml
> +version: 1.0.1
应该从 1.0.0 开始

2022-06-27 06:51 UTC, jeffyjf commented on charts/glance/templates/keystone-rbac.yaml
> +apiVersion: v1
研究一下，看看这个文件能不能简化，应该不需要这么多权限。

2022-07-07 10:27 UTC, caotingv commented on .github/workflows/install-openstack-glance.yaml
> +name: Install glance chart
我觉得可能是因为，当时common和openstack_dep都还没有合并，现有的操作只是把coomon中的一些操作移动到openstack_dep。所以我觉得当时action没有报错是正常的。

2022-07-13 02:23 UTC, fightdou commented on charts/glance/templates/deployment-api.yaml
> +            - mountPath: /var/log/kolla/galnce
单词拼写错误

2022-07-21 06:06 UTC, jeffyjf requested changes
就一个小问题：文件一般都建议以 \n 结尾，这个 patch 有些文件结尾没用空行

2022-07-21 06:30 UTC, caotingv commented
> 

已解决

2022-07-21 09:22 UTC, jeffyjf commented
在上传镜像的时候会报错：413 Request Entity Too Large: nginx，解决方案参考：https://stackoverflow.com/questions/64759983/nginx-ingress-returns-413-entity-too-large

2022-07-26 06:22 UTC, jeffyjf approved these changes

2022-07-26 08:13 UTC, merged